// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4grywGIZ9MlQe1vYMimK4A9tOiBsBAw',
    appId: '1:897030007203:web:1a919156021c064a0f9216',
    messagingSenderId: '897030007203',
    projectId: 'myfirebase-b9c9d',
    authDomain: 'myfirebase-b9c9d.firebaseapp.com',
    storageBucket: 'myfirebase-b9c9d.appspot.com',
    measurementId: 'G-WFRENV0LYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEaf0fLq9UV_h4-7-sq8bdjeUWmeCPkiQ',
    appId: '1:897030007203:android:a4249f27213bbaa30f9216',
    messagingSenderId: '897030007203',
    projectId: 'myfirebase-b9c9d',
    storageBucket: 'myfirebase-b9c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBi-yuMww-dpwhiJffRB21ENVJp9s9RMc',
    appId: '1:897030007203:ios:dca2f6b752e071730f9216',
    messagingSenderId: '897030007203',
    projectId: 'myfirebase-b9c9d',
    storageBucket: 'myfirebase-b9c9d.appspot.com',
    iosBundleId: 'com.jensen.cubitLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBi-yuMww-dpwhiJffRB21ENVJp9s9RMc',
    appId: '1:897030007203:ios:dca2f6b752e071730f9216',
    messagingSenderId: '897030007203',
    projectId: 'myfirebase-b9c9d',
    storageBucket: 'myfirebase-b9c9d.appspot.com',
    iosBundleId: 'com.jensen.cubitLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz4grywGIZ9MlQe1vYMimK4A9tOiBsBAw',
    appId: '1:897030007203:web:0475d03b12cafa680f9216',
    messagingSenderId: '897030007203',
    projectId: 'myfirebase-b9c9d',
    authDomain: 'myfirebase-b9c9d.firebaseapp.com',
    storageBucket: 'myfirebase-b9c9d.appspot.com',
    measurementId: 'G-4KWKSPL0G7',
  );
}
